// GENERATED BY BOLT.NEW – DO NOT EDIT MANUALLY

export interface Scene {
  id: string;
  text: string;
  dc: number;
  successText: string;
  failureText: string;
}

const scenes: Scene[] = [
  {
    id: "scene-1",
    text: "You find yourself at the edge of a misty forest. Ancient trees whisper secrets in the wind. A narrow path leads deeper into the shadows, while another route circles around the perimeter. Your guardian spirit watches silently, waiting for your choice.",
    dc: 10,
    successText: "Your intuition guides you well. The path reveals hidden runes that glow softly, marking safe passage. Your guardian spirit nods approvingly as you navigate the mystical terrain with confidence.",
    failureText: "The mist thickens around you, and you stumble over hidden roots. Though you find your way eventually, your guardian spirit's light dims slightly, sensing your uncertainty in this sacred place."
  },
  {
    id: "scene-2", 
    text: "A crystalline stream blocks your path, its waters shimmering with otherworldly energy. You can attempt to leap across the narrowest point, or search for stepping stones upstream. The current seems gentle, but appearances can be deceiving.",
    dc: 12,
    successText: "Your leap is graceful and sure, landing safely on the far bank. The stream's energy seems to recognize your courage, and small lights dance around you. Your guardian spirit glows brighter with pride.",
    failureText: "You misjudge the distance and splash into the cool water. Though unharmed, you emerge soaked and shivering. Your guardian spirit offers warmth, but you sense its concern for your hasty decision."
  },
  {
    id: "scene-3",
    text: "Before you stands an ancient stone door covered in glowing symbols. Three symbols pulse more brightly than the others - a star, a tree, and a flame. You must choose which symbol to touch to unlock the passage to your destiny.",
    dc: 14,
    successText: "The symbol responds to your touch with a warm, golden light. The door opens smoothly, revealing a chamber filled with gentle radiance. Your guardian spirit radiates joy - you have chosen wisely and proven your growing wisdom.",
    failureText: "The symbol flickers and dims under your touch. The door remains sealed, and you feel a wave of disappointment. Your guardian spirit dims as well, sharing in your struggle, but encourages you to learn from this moment."
  }
];

let currentSceneIndex = 0;

export const getCurrentScene = (): Scene => {
  return scenes[currentSceneIndex];
};

export const advanceScene = (): void => {
  if (currentSceneIndex < scenes.length - 1) {
    currentSceneIndex++;
  }
};

export const isLastScene = (): boolean => {
  return currentSceneIndex >= scenes.length - 1;
};

export const resetScenes = (): void => {
  currentSceneIndex = 0;
};

// Dice rolling utility
export interface DiceResult {
  roll: number;
  dc: number;
  success: boolean;
}

export const rollDice = (dc: number): DiceResult => {
  const roll = Math.floor(Math.random() * 20) + 1; // d20 roll
  return {
    roll,
    dc,
    success: roll >= dc
  };
};