// GENERATED BY BOLT.NEW â€" DO NOT EDIT MANUALLY

/**
 * Scene Engine - Core narrative and progression system for Luminari's Quest
 * 
 * This module manages the therapeutic storytelling experience, providing
 * 20 carefully crafted scenarios that guide players through emotional
 * growth and healing. Each scene represents a different aspect of trauma
 * recovery and therapeutic progress.
 * 
 * @module SceneEngine
 */

import { SHADOW_IDS } from '../data/shadowManifestations';

/**
 * Represents a single therapeutic scenario in the game
 * 
 * Each scene is designed to address specific therapeutic goals while
 * maintaining engaging gameplay. The structure supports multiple scene
 * types with varying difficulty levels and therapeutic focuses.
 */
export interface Scene {
  /** Unique identifier for the scene (kebab-case) */
  id: string;
  
  /** 
   * Scene type determining therapeutic focus:
   * - social: Interpersonal connection and empathy
   * - skill: Problem-solving and competence building
   * - combat: Confronting internal struggles
   * - journal: Self-reflection and processing
   * - exploration: Discovery and perspective-taking
   */
  type: 'social' | 'skill' | 'combat' | 'journal' | 'exploration';
  
  /** Display title for the scene (max 50 characters recommended) */
  title: string;
  
  /** Narrative description setting up the scenario (max 500 characters recommended) */
  text: string;
  
  /** Difficulty Check - target number for d20 roll (typically 10-20) */
  dc: number;
  
  /** Text displayed when the player succeeds the challenge */
  successText: string;
  
  /** Text displayed when the player fails the challenge */
  failureText: string;
  
  /** Available player choices for the scenario */
  choices: {
    /** Bold/aggressive choice option */
    bold: string;
    /** Cautious/thoughtful choice option */
    cautious: string;
  };
  
  // Combat integration properties
  /** Shadow manifestation type for combat scenes (references SHADOW_IDS) */
  shadowType?: string;
  
  /** Light Points awarded on success (overrides default if specified) */
  lpReward?: number;
  
  /** Shadow Points penalty on failure (overrides default if specified) */
  spPenalty?: number;
}

const scenes: Scene[] = [
  {
    id: 'social-encounter',
    type: 'social',
    title: 'The Worried Merchant',
    text: "A traveling merchant sits by the roadside, tears streaming down his weathered face. His cart is overturned, goods scattered. 'Bandits took everything,' he whispers. 'My family's livelihood... gone.' He looks up at you with desperate hope. You could offer comfort, share resources, or help him gather his belongings.",
    dc: 10,
    successText:
      "Your words of comfort and genuine care touch the merchant's heart. He stands straighter, hope returning to his eyes. 'Thank you, young one. Your kindness reminds me that good still exists in this world.' Your guardian spirit glows warmly, sensing your growing empathy.",
    failureText:
      "Despite your good intentions, your words feel hollow and awkward. The merchant nods politely but remains distant, his pain unchanged. Your guardian spirit dims slightly, recognizing your struggle to connect with others' suffering.",
    choices: {
      bold: 'Offer immediate help and comfort',
      cautious: 'Listen carefully before responding',
    },
  },
  {
    id: 'skill-challenge',
    type: 'skill',
    title: 'The Ancient Lock',
    text: 'Before you stands an ornate chest, its surface covered in intricate mechanisms and glowing runes. The lock appears to be a puzzle requiring both dexterity and wisdom to solve. Ancient symbols shift and change as you approach. This could contain something valuable, but one wrong move might trigger unknown consequences.',
    dc: 12,
    successText:
      'Your fingers move with surprising grace across the mechanisms. The runes align perfectly, and the chest opens with a satisfying click. Inside, you find a small crystal that pulses with warm light. Your guardian spirit radiates pride at your growing skill and patience.',
    failureText:
      'The mechanisms resist your efforts, and the runes flash angrily before going dark. The chest remains sealed, and you feel a wave of frustration. Your guardian spirit offers gentle encouragement, reminding you that failure is part of learning.',
    choices: {
      bold: 'Trust your instincts and work quickly',
      cautious: 'Study the patterns before acting',
    },
  },
  {
    id: 'combat-encounter',
    type: 'combat',
    title: 'Shadow Wolf',
    text: 'A creature of living shadow emerges from the darkness between the trees. Its eyes glow with an otherworldly hunger, and its form shifts like smoke. This shadow wolf blocks your path, growling low. You sense it feeds on fear and doubt. You must decide how to face this manifestation of inner darkness.',
    dc: 14,
    successText:
      'You stand firm against the shadow wolf, your inner light blazing bright. The creature recoils, then slowly dissolves back into harmless shadows. Your courage has banished this manifestation of fear. Your guardian spirit shines brilliantly, proud of your bravery.',
    failureText:
      "Fear grips your heart as the shadow wolf advances. Though you manage to escape unharmed, the creature's presence lingers in your mind. Your guardian spirit wraps you in protective warmth, helping you process this encounter with your inner fears.",
    choices: {
      bold: 'Face the wolf with courage and determination',
      cautious: 'Seek to understand what the wolf represents',
    },
    // Combat integration
    shadowType: SHADOW_IDS.WHISPER_OF_DOUBT,
    lpReward: 4,
    spPenalty: 3,
  },
  {
    id: 'journal-reflection',
    type: 'journal',
    title: 'The Memory Pool',
    text: 'You discover a still pool that reflects not your face, but memories from your past. Images of loss, moments of joy, times of struggle all shimmer on the surface. Your guardian spirit whispers that this is a place of healing, where you can choose to face difficult memories or let them remain buried for now.',
    dc: 11,
    successText:
      "You kneel by the pool and allow the memories to wash over you. Though some bring pain, you find strength in acknowledging them. The pool's surface clears, showing your reflection with new wisdom in your eyes. Your guardian spirit glows with gentle approval.",
    failureText:
      'The memories feel too overwhelming, and you step back from the pool. The images fade, leaving you feeling disconnected from your past. Your guardian spirit offers comfort, understanding that healing takes time and cannot be rushed.',
    choices: {
      bold: 'Dive deep into the difficult memories',
      cautious: 'Approach the memories gradually and gently',
    },
  },
  {
    id: 'exploration-discovery',
    type: 'exploration',
    title: 'The Singing Crystals',
    text: "You enter a cavern filled with luminescent crystals that hum with ethereal music. Each crystal seems to respond to your emotions, their songs shifting in harmony with your inner state. At the cavern's heart stands a larger crystal, its song more complex and beautiful than the others. You sense this place holds ancient wisdom.",
    dc: 13,
    successText:
      "You attune yourself to the crystals' song, letting their harmony guide your movements. The large crystal's music becomes clearer, revealing melodies that speak of hope, resilience, and growth. Your guardian spirit resonates with the crystals, creating a symphony of healing energy.",
    failureText:
      "The crystals' songs feel chaotic and overwhelming. You struggle to find harmony with their music, and the large crystal's song remains mysterious and distant. Your guardian spirit helps steady you, but you sense you've missed something important in this sacred place.",
    choices: {
      bold: 'Touch the central crystal immediately',
      cautious: 'Listen to the smaller crystals first',
    },
  },
  {
    id: 'social-gathering',
    type: 'social',
    title: 'The Village Festival',
    text: "You arrive at a small village during their harvest festival. Laughter and music fill the air, but you notice an elderly woman sitting alone on the outskirts, watching the celebration with longing eyes. She seems forgotten by the revelers, her weathered hands clutching a small, worn photograph. The joy around you contrasts sharply with her solitude.",
    dc: 11,
    successText:
      "You approach the elderly woman with genuine warmth, asking about the photograph and listening to her stories of past festivals. Her face lights up as she shares memories of her late husband, and soon others join your conversation. Your guardian spirit radiates joy as you help bridge the gap between generations.",
    failureText:
      "Your attempt to include the woman feels forced and uncomfortable. She smiles politely but retreats further into herself, and the other villagers seem to avoid the awkward interaction. Your guardian spirit offers gentle guidance, helping you understand that authentic connection cannot be rushed.",
    choices: {
      bold: 'Invite her to dance and celebrate with everyone',
      cautious: 'Sit with her and ask about her memories',
    },
  },
  {
    id: 'skill-navigation',
    type: 'skill',
    title: 'The Mist-Shrouded Path',
    text: 'A thick, supernatural mist has descended upon the mountain path ahead. Strange whispers echo from within, and the trail seems to shift and change before your eyes. Your map is useless here - only your intuition and careful observation can guide you through this maze of illusion. One wrong turn could lead you deeper into the mist\'s embrace.',
    dc: 15,
    successText:
      'You close your eyes and trust your inner compass, feeling for the subtle currents of air and listening to the true sounds beneath the whispers. Step by careful step, you navigate through the illusion, emerging into clear sunlight on the other side. Your guardian spirit glows with pride at your growing wisdom and self-trust.',
    failureText:
      'The mist\'s illusions overwhelm your senses, and you find yourself walking in circles. Panic begins to set in as the whispers grow louder, but eventually you stumble back to where you started, exhausted and shaken. Your guardian spirit wraps you in comfort, reminding you that getting lost sometimes teaches us where we truly belong.',
    choices: {
      bold: 'Push forward quickly before the mist thickens',
      cautious: 'Move slowly and test each step carefully',
    },
  },
  {
    id: 'combat-isolation',
    type: 'combat',
    title: 'The Veil of Isolation',
    text: 'A shimmering barrier of dark energy materializes around you, cutting you off from the world. Within this veil, you face a shadow that mirrors your own form but radiates loneliness and despair. It speaks with your voice, whispering of times you felt abandoned, forgotten, or completely alone. This manifestation of isolation seeks to convince you that connection is impossible.',
    dc: 16,
    successText:
      'You reach out toward the shadow-self with compassion rather than fear, acknowledging the pain of isolation while affirming your capacity for connection. The veil dissolves as you embrace both your solitude and your need for others. Your guardian spirit shines brilliantly, celebrating your courage to face your deepest fears of abandonment.',
    failureText:
      'The shadow\'s words cut deep, and you feel the familiar ache of loneliness overwhelming you. Though you resist being consumed entirely, the veil lingers, leaving you feeling disconnected and vulnerable. Your guardian spirit offers patient presence, reminding you that even in isolation, you are not truly alone.',
    choices: {
      bold: 'Challenge the shadow directly with your inner strength',
      cautious: 'Try to understand what the shadow needs from you',
    },
    // Combat integration
    shadowType: SHADOW_IDS.VEIL_OF_ISOLATION,
    lpReward: 5,
    spPenalty: 4,
  },
  {
    id: 'journal-crossroads',
    type: 'journal',
    title: 'The Crossroads of Choice',
    text: 'You stand at a crossroads where three paths diverge, each marked by a stone tablet covered in ancient script. As you approach, the tablets begin to glow, revealing not directions but questions about your life\'s journey. The middle path asks about your dreams, the left about your fears, and the right about your regrets. Your guardian spirit suggests this is a place for deep reflection.',
    dc: 12,
    successText:
      'You sit quietly at the crossroads and honestly examine each question, writing your thoughts in your journal. The process is challenging but illuminating, helping you see patterns in your choices and growth in your character. The tablets\' glow softens to a warm, welcoming light. Your guardian spirit radiates approval at your willingness to face difficult truths.',
    failureText:
      'The questions feel too overwhelming, and you struggle to find honest answers. Your journal entries feel shallow and evasive, avoiding the deeper truths the crossroads seeks to reveal. The tablets\' light dims, but doesn\'t disappear entirely. Your guardian spirit offers gentle encouragement, understanding that self-reflection is a skill that develops over time.',
    choices: {
      bold: 'Write boldly about your deepest truths and desires',
      cautious: 'Explore your thoughts carefully, one question at a time',
    },
  },
  {
    id: 'exploration-sanctuary',
    type: 'exploration',
    title: 'The Hidden Sanctuary',
    text: 'Behind a waterfall, you discover a hidden sanctuary carved into living rock. Bioluminescent plants provide gentle light, and a natural spring creates a peaceful melody. Ancient murals cover the walls, depicting scenes of healing, growth, and transformation. At the sanctuary\'s heart lies a garden where impossible flowers bloom - each one representing a different aspect of emotional healing.',
    dc: 14,
    successText:
      'You move through the sanctuary with reverence, studying each mural and tending to the healing flowers. As you care for the garden, you feel your own wounds beginning to mend. The sanctuary responds to your presence, revealing hidden chambers filled with wisdom about recovery and resilience. Your guardian spirit harmonizes with the sanctuary\'s ancient peace.',
    failureText:
      'The sanctuary\'s beauty overwhelms you, and you feel unworthy of its peace. You rush through without truly connecting to its healing energy, missing the deeper lessons the murals and flowers could teach. The sanctuary remains beautiful but distant, its secrets locked away. Your guardian spirit reminds you that healing spaces require patience and self-compassion to fully embrace.',
    choices: {
      bold: 'Immediately begin tending to the healing garden',
      cautious: 'Study the murals first to understand the sanctuary\'s purpose',
    },
  },
  {
    id: 'social-mentor',
    type: 'social',
    title: 'The Weary Teacher',
    text: "In a small schoolhouse, you meet an exhausted teacher struggling to reach a group of troubled students. Her eyes are red from sleepless nights, and her voice cracks with frustration. 'I don't know how to help them anymore,' she confesses. 'They've been through so much trauma, and I feel like I'm failing them every day.' She looks to you with desperate hope for guidance or understanding.",
    dc: 10,
    successText:
      "You share your own experiences with learning and growth, offering both practical suggestions and emotional support. Your words remind her why she became a teacher, reigniting her passion and hope. The students sense the renewed energy and begin to respond more positively. Your guardian spirit glows warmly, recognizing your ability to inspire others through your own journey.",
    failureText:
      "Your advice feels generic and unhelpful, missing the deeper emotional needs behind her struggle. The teacher nods politely but remains discouraged, and the classroom atmosphere stays tense. Your guardian spirit offers gentle understanding, reminding you that sometimes the most important thing is simply being present with someone's pain.",
    choices: {
      bold: 'Share your personal story of overcoming challenges',
      cautious: 'Ask her to tell you more about each student\'s needs',
    },
  },
  {
    id: 'skill-crafting',
    type: 'skill',
    title: 'The Broken Heirloom',
    text: 'You discover a shattered family heirloom - a beautiful music box that once played lullabies for generations of children. Its delicate mechanisms are scattered, and the melody disc is cracked. The pieces seem to whisper of lost memories and broken connections. Repairing it will require patience, precision, and an understanding of how broken things can be made whole again.',
    dc: 13,
    successText:
      'With careful attention and gentle hands, you piece together the music box. As the final gear clicks into place, it begins to play a hauntingly beautiful lullaby. The melody seems to heal something deep within you, reminding you that broken things can indeed be restored. Your guardian spirit resonates with the music, celebrating your growing ability to mend what seems irreparable.',
    failureText:
      'Despite your best efforts, the delicate mechanisms resist your attempts at repair. Pieces slip from your fingers, and the melody remains silent. Frustration builds as you realize some damage runs too deep for simple fixes. Your guardian spirit offers comfort, teaching you that sometimes accepting brokenness is the first step toward healing.',
    choices: {
      bold: 'Work quickly to restore the music before it\'s too late',
      cautious: 'Study each piece carefully before attempting repairs',
    },
  },
  {
    id: 'combat-overwhelm',
    type: 'combat',
    title: 'The Storm of Overwhelm',
    text: 'Dark clouds gather overhead, but this is no ordinary storm. Lightning crackles with the energy of every overwhelming moment you\'ve ever faced - bills unpaid, deadlines missed, relationships strained, futures uncertain. The storm speaks in a cacophony of voices: responsibilities, expectations, fears, and pressures all demanding attention at once. You feel yourself drowning in the chaos of too much, too fast, too heavy.',
    dc: 14,
    successText:
      'You stand in the eye of the storm and breathe deeply, acknowledging each overwhelming voice without letting them control you. One by one, you address what you can and release what you cannot. The storm gradually calms, its chaotic energy transforming into manageable rain. Your guardian spirit shines through the clearing clouds, proud of your growing ability to find peace within chaos.',
    failureText:
      'The storm\'s intensity overwhelms your defenses, and you feel yourself swept away by the torrent of pressures and fears. Though you eventually find shelter, the experience leaves you feeling small and powerless against life\'s demands. Your guardian spirit wraps you in protective warmth, reminding you that even the strongest people sometimes need to weather the storm rather than fight it.',
    choices: {
      bold: 'Stand firm and face each overwhelming voice directly',
      cautious: 'Find shelter and wait for the storm to pass naturally',
    },
    // Combat integration
    shadowType: SHADOW_IDS.STORM_OF_OVERWHELM,
    lpReward: 4,
    spPenalty: 3,
  },
  {
    id: 'journal-letters',
    type: 'journal',
    title: 'The Unsent Letters',
    text: 'In an abandoned post office, you find a collection of unsent letters - messages of love, apology, gratitude, and goodbye that were never delivered. Some are addressed to people who have passed away, others to relationships that ended badly. Your guardian spirit whispers that this is a place where you can write your own unsent letter to someone important in your life.',
    dc: 11,
    successText:
      'You sit among the letters and pour your heart onto paper, writing to someone you\'ve lost or someone you\'ve hurt. The words flow freely, carrying years of unspoken emotions. As you finish, you feel a weight lift from your shoulders. Your guardian spirit glows softly, understanding that some conversations happen in the heart even when they can\'t happen in person.',
    failureText:
      'You struggle to find the right words, and your letter feels stilted and incomplete. The emotions you want to express remain locked inside, too complex or painful to capture on paper. Your guardian spirit offers patient presence, knowing that some feelings need time to find their voice.',
    choices: {
      bold: 'Write everything you\'ve always wanted to say, holding nothing back',
      cautious: 'Start with small, simple truths and build from there',
    },
  },
  {
    id: 'exploration-library',
    type: 'exploration',
    title: 'The Library of Lost Stories',
    text: 'You discover a vast library where the books contain not written words, but the untold stories of people\'s lives - dreams abandoned, paths not taken, words never spoken. The shelves stretch endlessly upward, filled with the weight of human potential. At the center stands a reading desk with an open book that seems to be writing itself, chronicling your own story as you live it.',
    dc: 12,
    successText:
      'You approach the writing book with curiosity rather than fear, reading the story of your life with compassion for both your struggles and your growth. You realize that your story is still being written, and you have the power to influence its direction. Your guardian spirit radiates joy as you embrace your role as both author and protagonist of your own journey.',
    failureText:
      'The weight of all the untold stories overwhelms you, and you feel lost among the endless possibilities of what could have been. Your own story seems small and insignificant compared to the vast potential surrounding you. Your guardian spirit gently guides you away from the overwhelming shelves, reminding you that your story matters precisely because it is yours.',
    choices: {
      bold: 'Read your story aloud to give it power and presence',
      cautious: 'Quietly study your story to understand its patterns',
    },
  },
  {
    id: 'social-reconciliation',
    type: 'social',
    title: 'The Estranged Friend',
    text: "At a crowded marketplace, you unexpectedly encounter someone who was once your closest friend but became distant after a painful misunderstanding years ago. They notice you too, and for a moment, time stops. The hurt in their eyes mirrors your own, but there's also a flicker of the warmth you once shared. Other shoppers bustle around you, unaware of this moment of reckoning between two wounded hearts.",
    dc: 12,
    successText:
      "You take a deep breath and approach with genuine vulnerability, acknowledging the pain between you without defensiveness. Your friend's walls begin to crumble as you both share your perspectives with honesty and compassion. Though the conversation is difficult, it opens a door to healing that has been closed for too long. Your guardian spirit radiates hope, celebrating your courage to mend broken bonds.",
    failureText:
      "Pride and old hurt make your words come out wrong, and the conversation becomes awkward and strained. Your friend retreats behind familiar walls, and the moment passes without resolution. The marketplace crowd seems to swallow the opportunity for healing. Your guardian spirit offers gentle comfort, reminding you that some reconciliations require multiple attempts and perfect timing.",
    choices: {
      bold: 'Approach immediately and address the past directly',
      cautious: 'Make gentle eye contact and see if they want to talk',
    },
  },
  {
    id: 'skill-restoration',
    type: 'skill',
    title: 'The Withered Garden',
    text: 'You come upon a once-magnificent garden now choked with weeds and neglect. Beneath the overgrowth, you can see hints of what it used to be - rare flowers struggling to bloom, fruit trees heavy with unpicked harvest, pathways obscured but not destroyed. A weathered sign reads "Memorial Garden - In loving memory of those we\'ve lost." This place needs more than gardening; it needs someone who understands that growth can emerge from grief.',
    dc: 14,
    successText:
      'You work with patient reverence, clearing weeds while preserving the struggling plants beneath. As you tend to each section, the garden begins to reveal its hidden beauty. Flowers bloom more vibrantly, and the memorial stones become visible again, each one honoring a life well-lived. Your guardian spirit glows with quiet satisfaction, recognizing your understanding that healing spaces require both effort and respect.',
    failureText:
      'Your enthusiasm leads you to work too quickly, accidentally damaging some of the delicate plants you meant to save. The garden resists your efforts, and you realize that restoration requires more patience and understanding than you initially brought to the task. Your guardian spirit offers gentle guidance, teaching you that some healing cannot be rushed.',
    choices: {
      bold: 'Clear the largest areas first to make dramatic progress',
      cautious: 'Work carefully around each plant to preserve what remains',
    },
  },
  {
    id: 'combat-past-pain',
    type: 'combat',
    title: 'The Echo of Past Pain',
    text: 'The air around you shimmers, and suddenly you\'re surrounded by ghostly echoes of your most painful memories. They don\'t just replay - they speak, accusing you of weakness, reminding you of every moment you felt helpless, abandoned, or broken. The echoes take the form of shadowy figures from your past, their voices layering into a chorus of old wounds. This manifestation feeds on unhealed trauma, growing stronger with each painful memory it can awaken.',
    dc: 15,
    successText:
      'You face the echoes with hard-won wisdom, acknowledging the pain they represent while refusing to let them define you. "You are part of my story," you tell them, "but you are not the end of it." The shadows begin to fade as you embrace both your wounds and your healing. Your guardian spirit blazes with fierce pride, celebrating your transformation of pain into strength.',
    failureText:
      'The echoes overwhelm you with their familiar sting, and you feel yourself pulled back into old patterns of hurt and helplessness. Though you don\'t surrender completely, the encounter leaves you feeling raw and vulnerable, as if old scabs have been torn away. Your guardian spirit surrounds you with protective warmth, reminding you that healing isn\'t linear and setbacks don\'t erase progress.',
    choices: {
      bold: 'Confront each painful memory with your current strength',
      cautious: 'Acknowledge the pain while focusing on how you\'ve grown',
    },
    // Combat integration
    shadowType: SHADOW_IDS.ECHO_OF_PAST_PAIN,
    lpReward: 4,
    spPenalty: 3,
  },
  {
    id: 'journal-legacy',
    type: 'journal',
    title: 'The Time Capsule',
    text: 'You discover an old time capsule buried beneath a great oak tree, filled with letters, photos, and mementos from people who wanted to leave something for the future. Among the items, you find a blank journal with a note: "For whoever finds this - tell us about the world you\'re building from the ashes of ours." Your guardian spirit whispers that this is an opportunity to reflect on what you want to leave behind for those who come after you.',
    dc: 13,
    successText:
      'You write with deep thoughtfulness about the lessons you\'ve learned, the love you\'ve discovered, and the hope you carry for the future. Your words become a bridge between past and future, honoring those who came before while inspiring those yet to come. The journal seems to glow with purpose as you write. Your guardian spirit radiates warmth, recognizing your growing understanding of your place in the larger story of healing.',
    failureText:
      'You struggle to find words worthy of such a profound opportunity. Your writing feels inadequate to capture the complexity of your journey or the depth of what you want to share. The blank pages seem to mock your efforts to articulate something meaningful. Your guardian spirit offers patient encouragement, reminding you that sometimes the most important messages are the simplest ones.',
    choices: {
      bold: 'Write about your biggest dreams and hopes for the future',
      cautious: 'Share the most important lessons you\'ve learned so far',
    },
  },
  {
    id: 'exploration-summit',
    type: 'exploration',
    title: 'The Summit of Reflection',
    text: 'After a long, winding climb, you reach the summit of a mountain that overlooks the entire landscape of your journey. From this vantage point, you can see all the places you\'ve been - the dark valleys, the peaceful meadows, the rushing rivers, and the quiet forests. The view stretches to the horizon, showing paths you haven\'t yet taken. At the summit\'s peak stands a simple stone chair, worn smooth by countless other travelers who have sat here to contemplate their journeys.',
    dc: 14,
    successText:
      'You sit in the ancient chair and let the full scope of your journey wash over you. From this height, even your darkest moments seem part of a larger pattern of growth and discovery. You feel a deep sense of accomplishment not just for reaching this summit, but for every step that brought you here. Your guardian spirit shines brilliantly, sharing in your moment of profound recognition and peace.',
    failureText:
      'The vastness of the view overwhelms you, and instead of feeling accomplished, you feel small and uncertain about the path ahead. The summit\'s perspective makes your problems seem both insignificant and insurmountable at the same time. Your guardian spirit settles beside you with gentle presence, reminding you that sometimes the most important view is not the distant horizon, but the solid ground beneath your feet.',
    choices: {
      bold: 'Stand tall and proclaim your growth to the world below',
      cautious: 'Sit quietly and absorb the wisdom of the journey',
    },
  },
];

export const getScene = (index: number): Scene => {
  return scenes[index];
};

export const isLastScene = (index: number): boolean => {
  return index >= scenes.length - 1;
};

export const getSceneProgress = (index: number): { current: number; total: number } => {
  return {
    current: index + 1,
    total: scenes.length,
  };
};

/**
 * Result of a dice roll against a difficulty check
 */
export interface DiceResult {
  /** The actual d20 roll result (1-20) */
  roll: number;
  /** The difficulty check target number */
  dc: number;
  /** Whether the roll succeeded (roll >= dc) */
  success: boolean;
}

/**
 * Performs a d20 dice roll against a difficulty check
 * 
 * This function simulates rolling a 20-sided die and comparing it against
 * a difficulty check (DC). Success occurs when the roll meets or exceeds
 * the DC. This mechanic adds uncertainty and excitement to scene outcomes.
 * 
 * @param dc - Difficulty Check target number (typically 10-20)
 * @returns DiceResult containing roll value, DC, and success status
 * 
 * @example
 * ```typescript
 * const result = rollDice(15);
 * console.log(`Rolled ${result.roll} vs DC ${result.dc}`);
 * if (result.success) {
 *   console.log("Success!");
 * }
 * ```
 */
export const rollDice = (dc: number): DiceResult => {
  const roll = Math.floor(Math.random() * 20) + 1; // d20 roll
  return {
    roll,
    dc,
    success: roll >= dc,
  };
};

/**
 * Represents the complete outcome of a scene interaction
 * 
 * This interface captures all the results of a player's scene choice,
 * including success/failure, resource changes, and potential combat triggers.
 */
export interface SceneOutcome {
  /** The scene that was processed */
  scene: Scene;
  /** Whether the player succeeded in the scene challenge */
  success: boolean;
  /** The dice roll result (if applicable) */
  roll?: number;
  /** Whether this outcome triggered a combat encounter */
  triggeredCombat?: boolean;
  /** The type of shadow manifestation for combat (if triggered) */
  shadowType?: string;
  /** Changes to player resources (Light Points/Shadow Points) */
  resourceChanges?: {
    /** Change in Light Points (positive = gain, negative = loss) */
    lpChange?: number;
    /** Change in Shadow Points (positive = gain, negative = loss) */
    spChange?: number;
  };
}

/**
 * Processes the outcome of a scene interaction
 * 
 * This function handles the complete resolution of a scene, including:
 * - Determining resource rewards/penalties
 * - Triggering combat encounters for failed combat scenes
 * - Applying scene-specific or default resource changes
 * 
 * @param scene - The scene being processed
 * @param success - Whether the player succeeded in the challenge
 * @param roll - The dice roll result (optional)
 * @returns Complete scene outcome with all effects
 * 
 * @example
 * ```typescript
 * const scene = getScene(0);
 * const diceResult = rollDice(scene.dc);
 * const outcome = handleSceneOutcome(scene, diceResult.success, diceResult.roll);
 * 
 * if (outcome.triggeredCombat) {
 *   // Start combat with outcome.shadowType
 * } else {
 *   // Apply resource changes
 *   updateResources(outcome.resourceChanges);
 * }
 * ```
 */
export const handleSceneOutcome = (
  scene: Scene,
  success: boolean,
  roll?: number
): SceneOutcome => {
  const outcome: SceneOutcome = {
    scene,
    success,
    roll,
    triggeredCombat: false,
    resourceChanges: {}
  };

  // Combat scene trigger - failed combat scenes trigger shadow battles
  if (scene.type === 'combat' && !success && scene.shadowType) {
    outcome.triggeredCombat = true;
    outcome.shadowType = scene.shadowType;
    // No immediate resource changes - combat will handle rewards/penalties
    return outcome;
  }

  // Award resources based on outcome for non-combat scenes
  if (success) {
    // Success rewards Light Points
    const lpReward = scene.lpReward || getDefaultLPReward(scene.type);
    outcome.resourceChanges!.lpChange = lpReward;
  } else {
    // Failure penalties Shadow Points
    const spPenalty = scene.spPenalty || getDefaultSPPenalty(scene.type);
    outcome.resourceChanges!.spChange = spPenalty;
  }

  return outcome;
};

/**
 * Gets default LP reward for successful scenes by type
 */
const getDefaultLPReward = (sceneType: Scene['type']): number => {
  switch (sceneType) {
    case 'social': return 3;
    case 'skill': return 2;
    case 'combat': return 4; // Higher reward for combat success
    case 'journal': return 2;
    case 'exploration': return 3;
    default: return 2;
  }
};

/**
 * Gets default SP penalty for failed scenes by type
 */
const getDefaultSPPenalty = (sceneType: Scene['type']): number => {
  switch (sceneType) {
    case 'social': return 2;
    case 'skill': return 1;
    case 'combat': return 3; // Higher penalty for combat failure
    case 'journal': return 1;
    case 'exploration': return 2;
    default: return 1;
  }
};

/**
 * Maps scene IDs to appropriate shadow types for combat encounters
 */
export const mapSceneToShadowType = (sceneId: string): string => {
  // Map specific scenes to specific shadows
  const sceneToShadowMap: Record<string, string> = {
    'combat-encounter': SHADOW_IDS.WHISPER_OF_DOUBT,
    'combat-isolation': SHADOW_IDS.VEIL_OF_ISOLATION,
    'combat-overwhelm': SHADOW_IDS.STORM_OF_OVERWHELM,
    'combat-past-pain': SHADOW_IDS.ECHO_OF_PAST_PAIN,
    // Add more mappings as needed
  };

  return sceneToShadowMap[sceneId] || SHADOW_IDS.WHISPER_OF_DOUBT;
};
