// GENERATED BY BOLT.NEW – DO NOT EDIT MANUALLY

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { getCurrentScene, advanceScene, rollDice, isLastScene, type DiceResult } from '@/engine/scene-engine';
import { DiceRollOverlay } from './DiceRollOverlay';

interface ChoiceListProps {
  onSceneComplete?: () => void;
}

export function ChoiceList({ onSceneComplete }: ChoiceListProps) {
  const [showDiceRoll, setShowDiceRoll] = useState(false);
  const [diceResult, setDiceResult] = useState<DiceResult | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);

  const currentScene = getCurrentScene();

  const handleChoice = (choiceIndex: number) => {
    if (isProcessing) return;
    
    setIsProcessing(true);
    const result = rollDice(currentScene.dc);
    setDiceResult(result);
    setShowDiceRoll(true);
  };

  const handleDiceRollClose = () => {
    if (!diceResult) return;

    setShowDiceRoll(false);
    
    // Update guardian trust and message (these would come from context in full implementation)
    // For MVP, we'll just advance the scene
    
    if (!isLastScene()) {
      advanceScene();
    }
    
    setIsProcessing(false);
    setDiceResult(null);
    
    if (onSceneComplete) {
      onSceneComplete();
    }
  };

  if (isLastScene() && !showDiceRoll) {
    return (
      <Card className="w-full max-w-2xl mx-auto">
        <CardHeader>
          <CardTitle>Journey Complete</CardTitle>
          <CardDescription>
            You have completed this chapter of your adventure. Your guardian spirit has learned much about your choices and growth.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Button 
            onClick={() => window.location.reload()} 
            className="w-full"
          >
            Begin New Journey
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card className="w-full max-w-2xl mx-auto">
        <CardHeader>
          <CardTitle>Your Path Awaits</CardTitle>
          <CardDescription>
            Choose your approach to this challenge. Your guardian spirit watches and learns from your decisions.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="prose prose-sm max-w-none">
            <p className="text-foreground leading-relaxed">
              {currentScene.text}
            </p>
          </div>
          
          <div className="space-y-3">
            <Button
              onClick={() => handleChoice(0)}
              disabled={isProcessing}
              className="w-full justify-start h-auto p-4 text-left"
              variant="outline"
            >
              <div>
                <div className="font-medium">Take the bold approach</div>
                <div className="text-sm text-muted-foreground mt-1">
                  Trust your instincts and act decisively
                </div>
              </div>
            </Button>
            
            <Button
              onClick={() => handleChoice(1)}
              disabled={isProcessing}
              className="w-full justify-start h-auto p-4 text-left"
              variant="outline"
            >
              <div>
                <div className="font-medium">Take the cautious approach</div>
                <div className="text-sm text-muted-foreground mt-1">
                  Observe carefully and proceed with wisdom
                </div>
              </div>
            </Button>
          </div>
          
          <div className="text-xs text-muted-foreground text-center">
            Difficulty: {currentScene.dc} • Your choice will be tested by fate
          </div>
        </CardContent>
      </Card>

      {showDiceRoll && diceResult && (
        <DiceRollOverlay
          result={diceResult}
          onClose={handleDiceRollClose}
        />
      )}
    </>
  );
}