// GENERATED BY BOLT.NEW – DO NOT EDIT MANUALLY

import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dice6 } from 'lucide-react';
import { type DiceResult } from '@/engine/scene-engine';

interface DiceRollOverlayProps {
  result: DiceResult;
  onClose: () => void;
}

export function DiceRollOverlay({ result, onClose }: DiceRollOverlayProps) {
  const [isVisible, setIsVisible] = useState(false);
  const [showResult, setShowResult] = useState(false);

  const handleClose = () => {
    setIsVisible(false);
    setTimeout(onClose, 300);
  };

  useEffect(() => {
    setIsVisible(true);

    const resultTimer = setTimeout(() => {
      setShowResult(true);
    }, 800);

    const closeTimer = setTimeout(() => {
      handleClose();
    }, 7000);

    return () => {
      clearTimeout(resultTimer);
      clearTimeout(closeTimer);
    };
  }, [handleClose]);

  return (
    <div
      className={`fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm transition-opacity duration-300 ${
        isVisible ? 'opacity-100' : 'opacity-0'
      }`}
      onClick={handleClose}
    >
      <Card
        className={`bg-background/95 border-border/50 mx-4 w-96 transform border shadow-2xl backdrop-blur-sm transition-all duration-300 ${
          isVisible ? 'scale-100 opacity-100' : 'scale-95 opacity-0'
        }`}
        onClick={(e) => e.stopPropagation()}
      >
        <CardHeader className="pb-2 text-center">
          <CardTitle className="flex items-center justify-center gap-3 text-2xl font-bold combat-text-light">
            <Dice6 className={`h-7 w-7 ${!showResult ? 'animate-spin' : ''} text-white`} />
            Fate&apos;s Decision
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6 py-6 text-center">
          {!showResult ? (
            <div className="space-y-3">
              <div className="animate-pulse text-3xl font-bold text-foreground">Rolling...</div>
              <div className="text-base text-muted-foreground">
                Target: <span className="font-medium text-foreground">{result.dc}</span>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="space-y-1">
                <div className="bg-gradient-to-b from-white to-gray-200 bg-clip-text text-7xl font-extrabold text-transparent">
                  {result.roll}
                </div>
                <div className="text-base text-white/80">
                  vs <span className="font-medium text-white">DC {result.dc}</span>
                </div>
              </div>

              <div
                className={`text-2xl font-bold ${
                  result.success ? 'combat-text-heal' : 'combat-text-critical'
                }`}
              >
                {result.success ? '✨ Success!' : '💡 Try Again'}
              </div>

              <Button
                onClick={handleClose}
                variant={result.success ? 'default' : 'outline'}
                size="lg"
                className={`mt-2 h-11 rounded-full px-8 text-base ${
                  result.success
                    ? 'bg-primary hover:bg-primary/90'
                    : 'border-amber-500/30 combat-text-critical hover:bg-amber-500/10'
                }`}
              >
                Continue
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
