// GENERATED BY BOLT.NEW – DO NOT EDIT MANUALLY

import { useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Heart, Sparkles } from 'lucide-react';

interface GuardianTextProps {
  trust: number;
  message: string;
  className?: string;
}

export function GuardianText({ trust, message, className }: GuardianTextProps) {
  useEffect(() => {
    const handleStorageChange = () => {
      // Listen to guardian state changes
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const getTrustColor = (trustLevel: number) => {
    if (trustLevel >= 80) return 'bg-green-500';
    if (trustLevel >= 60) return 'bg-blue-500';
    if (trustLevel >= 40) return 'bg-yellow-500';
    if (trustLevel >= 20) return 'bg-orange-500';
    return 'bg-red-500';
  };

  const getTrustLabel = (trustLevel: number) => {
    if (trustLevel >= 80) return 'Deep Bond';
    if (trustLevel >= 60) return 'Strong Trust';
    if (trustLevel >= 40) return 'Growing Bond';
    if (trustLevel >= 20) return 'Cautious Trust';
    return 'Fragile Bond';
  };

  return (
    <Card className={className}>
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-lg">
          <Sparkles className="h-5 w-5 text-purple-500" />
          Guardian Spirit
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="prose prose-sm max-w-none">
          <p className="text-foreground leading-relaxed italic">
            "{message}"
          </p>
        </div>
        
        <div className="space-y-2">
          <div className="flex items-center justify-between text-sm">
            <span className="flex items-center gap-1">
              <Heart className="h-4 w-4 text-red-500" />
              Trust Bond
            </span>
            <span className="font-medium">
              {getTrustLabel(trust)}
            </span>
          </div>
          
          <div className="w-full bg-gray-200 rounded-full h-2 overflow-hidden">
            <div 
              className={`h-full transition-all duration-500 ${getTrustColor(trust)}`}
              style={{ width: `${trust}%` }}
            />
          </div>
          
          <div className="text-xs text-muted-foreground text-center">
            {trust}/100
          </div>
        </div>
      </CardContent>
    </Card>
  );
}