// GENERATED BY BOLT.NEW – DO NOT EDIT MANUALLY

import { Card, CardContent } from '@/components/ui/card';
import { Shield, Zap, Star, Sparkles, Sword } from 'lucide-react';
import { useGameStore } from '@/store/game-store';

interface StatsBarProps {
  trust: number;
  health?: number;
  energy?: number;
  experience?: number;
  className?: string;
  /** Show combat resources (Light/Shadow Points) - defaults to auto-detect based on player progress */
  showCombatResources?: boolean;
  /** Additional props to forward to the Card component */
  [key: string]: any;
}

export function StatsBar({
  trust: _trust,
  health, // Optional override - if not provided, uses store value
  energy = 100,
  experience = 0,
  className,
  showCombatResources,
  ...props
}: StatsBarProps) {
  const { lightPoints, shadowPoints, playerHealth } = useGameStore();

  // Use store health if no override provided
  const displayHealth = health ?? playerHealth;

  // Auto-detect if combat resources should be shown
  // Show if explicitly requested, or if player has any combat resources
  const shouldShowCombatResources = showCombatResources ?? (lightPoints > 0 || shadowPoints > 0);

  return (
    <Card className={className} {...props}>
      <CardContent className="space-y-4 p-4">
        {/* Trust Bond display removed - handled by GuardianText component */}

        {/* Combat Resources Section */}
        {shouldShowCombatResources && (
          <>
            {/* Combat Resources */}
            <div className="rounded-lg border border-amber-200 bg-gradient-to-r from-amber-50 to-purple-50 p-3 dark:border-amber-800 dark:from-amber-950/20 dark:to-purple-950/20">
              <div className="mb-3">
                <span className="text-sm font-semibold combat-text-critical">
                  Combat Resources
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3">
                {/* Light Points */}
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-amber-400 flex items-center justify-center">
                    <Sparkles className="w-4 h-4 text-white" />
                  </div>
                  <div>
                    <p className="text-xs font-medium text-muted-foreground">Light Points</p>
                    <p className="text-lg font-bold combat-text-critical">
                      {lightPoints}
                    </p>
                  </div>
                </div>

                {/* Shadow Points */}
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center">
                    <Sword className="w-4 h-4 text-white" />
                  </div>
                  <div>
                    <p className="text-xs font-medium text-muted-foreground">Shadow Points</p>
                    <p className="text-lg font-bold combat-text-mana">
                      {shadowPoints}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </>
        )}

        {/* Other Stats */}
        {/* Add divider only if combat resources are shown */}
        {shouldShowCombatResources && <hr className="border-muted" />}
        <div className="grid grid-cols-1 gap-3">
          <div className="flex items-center justify-between">
            <span className="flex items-center gap-2 text-sm font-medium">
              <Shield className="h-4 w-4 combat-text-heal" />
              Health
            </span>
            <div className="flex items-center gap-2">
              <div className="h-2 w-16 rounded-full bg-gray-200 dark:bg-gray-700">
                <div
                  className="h-full rounded-full bg-green-500 transition-all duration-300"
                  style={{ width: `${displayHealth}%` }}
                />
              </div>
              <span className="w-8 text-right text-xs font-medium">{displayHealth}</span>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <span className="flex items-center gap-2 text-sm font-medium">
              <Zap className="h-4 w-4 combat-text-mana" />
              Energy
            </span>
            <div className="flex items-center gap-2">
              <div className="h-2 w-16 rounded-full bg-gray-200 dark:bg-gray-700">
                <div
                  className="h-full rounded-full bg-blue-500 transition-all duration-300"
                  style={{ width: `${energy}%` }}
                />
              </div>
              <span className="w-8 text-right text-xs font-medium">{energy}</span>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <span className="flex items-center gap-2 text-sm font-medium">
              <Star className="h-4 w-4 combat-text-critical" />
              Experience
            </span>
            <div className="flex items-center gap-2">
              <div className="h-2 w-16 rounded-full bg-gray-200 dark:bg-gray-700">
                <div
                  className="h-full rounded-full bg-yellow-500 transition-all duration-300"
                  style={{ width: `${Math.min(100, experience)}%` }}
                />
              </div>
              <span className="w-8 text-right text-xs font-medium">{experience}</span>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
